# Site settings
name: 室内室外
email: 593829901@qq.com
author: Daun
url: 
resume_site: 
github: 
baseurl: ""
description: Hello, word!
meta_description: Daun;个人博客
motto: Hello, word.
banner:  ;

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: lintaoonline
# highlighter: Pygments

# Build settings
markdown: kramdown

FB:
  comments :
    provider : duoshuo
    duoshuo:
        short_name : lintaoonline
    disqus :
        short_name : 
    # facebook :
    #   appid : 123
    #   num_posts: 5
    #   width: 580
    #   colorscheme: light
